version: '3.3'

services:
  transcripts-BERT:
    image: hubertbaginski/transcripts:latest
    container_name: transcripts
    environment:
      - APP_PARAMS=--batch_size 4 --epochs 20 --checkpoint_folder /checkpoint_folder --variable_code MF01
    shm_size: '2gb'
    volumes:
      - /home/cept/hubert/checkpoints:/checkpoint_folder
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
